{"level":"info","message":"Conexión a PostgreSQL exitosa","timestamp":"2025-03-26 22:01:12"}
{"level":"info","message":"Servidor listo en el puerto: 4000","timestamp":"2025-03-26 22:01:12"}
{"level":"info","message":"Documentacion de Apis con Swagger en http://localhost:4000/api-docs","timestamp":"2025-03-26 22:01:12"}
{"code":"28P01","file":"auth.c","length":114,"level":"error","line":"338","message":"Error al conectar a la base de datos la autentificaci�n password fall� para el usuario �postgres�","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: la autentificaci�n password fall� para el usuario �postgres�\n    at C:\\Users\\52618\\Documentos\\UTD\\Cuatrimestre_8\\Desarrollo_Web_Profesional\\FactoresXBack\\FactoresX\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async testConnectionPostgreSQL (C:\\Users\\52618\\Documentos\\UTD\\Cuatrimestre_8\\Desarrollo_Web_Profesional\\FactoresXBack\\FactoresX\\src\\config\\configDB.ts:17:7)\n    at async startServerExpress (C:\\Users\\52618\\Documentos\\UTD\\Cuatrimestre_8\\Desarrollo_Web_Profesional\\FactoresXBack\\FactoresX\\src\\index.ts:48:5)","timestamp":"2025-03-29 16:24:48"}
{"level":"info","message":"Conexión a PostgreSQL exitosa","timestamp":"2025-03-29 16:27:08"}
{"level":"info","message":"Servidor listo en el puerto: 4000","timestamp":"2025-03-29 16:27:08"}
{"level":"info","message":"Documentacion de Apis con Swagger en http://localhost:4000/api-docs","timestamp":"2025-03-29 16:27:08"}
{"level":"info","message":"Conexión a PostgreSQL exitosa","timestamp":"2025-03-29 18:44:24"}
{"level":"info","message":"Servidor listo en el puerto: 4000","timestamp":"2025-03-29 18:44:24"}
{"level":"info","message":"Documentacion de Apis con Swagger en http://localhost:4000/api-docs","timestamp":"2025-03-29 18:44:24"}
{"level":"error","message":"Error creando el cuestionario: no existe la relación «cuestionarios»","timestamp":"2025-03-29 18:52:56"}
{"level":"error","message":"Error al crear el cuestionario Error interno al crear el cuestionario","stack":"Error: Error interno al crear el cuestionario\n    at crearCuestionario (C:\\Users\\52618\\Documentos\\UTD\\Cuatrimestre_8\\Desarrollo_Web_Profesional\\FactoresXBack\\FactoresX\\src\\services\\cuestionarioServices.ts:21:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async nuevoCuestionario (C:\\Users\\52618\\Documentos\\UTD\\Cuatrimestre_8\\Desarrollo_Web_Profesional\\FactoresXBack\\FactoresX\\src\\controller\\cuestionarioController.ts:18:35)","timestamp":"2025-03-29 18:52:56"}
{"level":"error","message":"Error creando el cuestionario: no existe la relación «cuestionarios»","timestamp":"2025-03-29 18:52:57"}
{"level":"error","message":"Error al crear el cuestionario Error interno al crear el cuestionario","stack":"Error: Error interno al crear el cuestionario\n    at crearCuestionario (C:\\Users\\52618\\Documentos\\UTD\\Cuatrimestre_8\\Desarrollo_Web_Profesional\\FactoresXBack\\FactoresX\\src\\services\\cuestionarioServices.ts:21:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async nuevoCuestionario (C:\\Users\\52618\\Documentos\\UTD\\Cuatrimestre_8\\Desarrollo_Web_Profesional\\FactoresXBack\\FactoresX\\src\\controller\\cuestionarioController.ts:18:35)","timestamp":"2025-03-29 18:52:57"}
{"code":"42P01","file":"parse_relation.c","length":114,"level":"error","line":"1452","message":"Error al obtener cuestionarios con preguntas: no existe la relación «cuestionarios»","name":"error","position":"370","routine":"parserOpenTable","severity":"ERROR","stack":"error: no existe la relación «cuestionarios»\n    at C:\\Users\\52618\\Documentos\\UTD\\Cuatrimestre_8\\Desarrollo_Web_Profesional\\FactoresXBack\\FactoresX\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async obtenerCuestionariosConPreguntas (C:\\Users\\52618\\Documentos\\UTD\\Cuatrimestre_8\\Desarrollo_Web_Profesional\\FactoresXBack\\FactoresX\\src\\services\\cuestionarioServices.ts:27:20)\n    at async cuestionarioConPreguntas (C:\\Users\\52618\\Documentos\\UTD\\Cuatrimestre_8\\Desarrollo_Web_Profesional\\FactoresXBack\\FactoresX\\src\\controller\\cuestionarioController.ts:34:29)","timestamp":"2025-03-29 18:54:48"}
{"level":"error","message":"Error en controlador al listar cuestionarios: No se pudo obtener la información","stack":"Error: No se pudo obtener la información\n    at obtenerCuestionariosConPreguntas (C:\\Users\\52618\\Documentos\\UTD\\Cuatrimestre_8\\Desarrollo_Web_Profesional\\FactoresXBack\\FactoresX\\src\\services\\cuestionarioServices.ts:52:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async cuestionarioConPreguntas (C:\\Users\\52618\\Documentos\\UTD\\Cuatrimestre_8\\Desarrollo_Web_Profesional\\FactoresXBack\\FactoresX\\src\\controller\\cuestionarioController.ts:34:29)","timestamp":"2025-03-29 18:54:48"}
{"code":"3D000","file":"postinit.c","length":108,"level":"error","line":"1050","message":"Error al conectar a la base de datos no existe la base de datos �cuestionario_nom035�","name":"error","routine":"InitPostgres","severity":"FATAL","stack":"error: no existe la base de datos �cuestionario_nom035�\n    at C:\\Users\\52618\\Documentos\\UTD\\Cuatrimestre_8\\Desarrollo_Web_Profesional\\FactoresXBack\\FactoresX\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async testConnectionPostgreSQL (C:\\Users\\52618\\Documentos\\UTD\\Cuatrimestre_8\\Desarrollo_Web_Profesional\\FactoresXBack\\FactoresX\\src\\config\\configDB.ts:17:7)\n    at async startServerExpress (C:\\Users\\52618\\Documentos\\UTD\\Cuatrimestre_8\\Desarrollo_Web_Profesional\\FactoresXBack\\FactoresX\\src\\index.ts:48:5)","timestamp":"2025-03-29 21:49:45"}
{"level":"info","message":"Conexión a PostgreSQL exitosa","timestamp":"2025-03-29 21:50:06"}
{"level":"info","message":"Servidor listo en el puerto: 4000","timestamp":"2025-03-29 21:50:06"}
{"level":"info","message":"Documentacion de Apis con Swagger en http://localhost:4000/api-docs","timestamp":"2025-03-29 21:50:06"}
{"level":"info","message":"Conexión a PostgreSQL exitosa","timestamp":"2025-03-30 08:52:26"}
{"level":"info","message":"Servidor listo en el puerto: 4000","timestamp":"2025-03-30 08:52:26"}
{"level":"info","message":"Documentacion de Apis con Swagger en http://localhost:4000/api-docs","timestamp":"2025-03-30 08:52:26"}
